; TheNetNode Configuration File
;
; DO NOT CHANGE THE ORDER OF THE CONFIGURATION LINES !
; DO NOT CLEAR ANY LINES !
;
; NET/ROM-Sysop-Password, 80 Characters (01234567890123...)
12345678901234567890123456789012345678901234567890123456789012345678901234567890
;
; Console Password
m
;
; Node Ident (Test)
TEST
;
; Node MyCall (XX0XX)
CB1GRH
;
; Workpath, Path to the Help-Files (TNN\)
; TNN should be started from this path.
F:\BACKUP\TNN\
;
; Path to the executable Text-Files (TNN\TEXTCMD\)
F:\BACKUP\TNN\TEXTCMD\
;
; Path to the extern Programs for User (TNN\USEREXE\)
F:\BACKUP\TNN\USEREXE\
;
; Path to the extern Programs only for Sysop (TNN\SYSEXE\)
F:\BACKUP\TNN\SYSEXE\
;
; Path fuer HTML (/usr/local/httpd/htdocs/)
F:\BACKUP\TNN\PACSAT\
;
; Path fuer HTML (/usr/local/httpd/htdocs/)
F:\BACKUP\TNN\HTTP\
